INSERT INTO card_data (id, name, data_json, enabled) VALUES 
('healing_amulet', '治疗护符', '{"id": "healing_amulet", "name": "治疗护符", "cardType": "AMULET", "cost": 2, "rarity": "BRONZE", "race": [], "job": "牧师", "keywords": [], "description": "倒数3。回合结束时，恢复我方主战者2点生命", "countdown": 3, "effects": [{"timing": "EndTurn", "type": "HEAL", "target": "MY_LEADER", "params": {"amount": 2}}]}', true),
('angel_blessing', '天使祝福', '{"id": "angel_blessing", "name": "天使祝福", "cardType": "SPELL", "cost": 2, "rarity": "BRONZE", "race": [], "job": "牧师", "keywords": [], "description": "恢复我方主战者5点生命，并抽1张牌", "effects": [{"timing": "Entering", "type": "HEAL", "target": "MY_LEADER", "params": {"amount": 5}}, {"timing": "Entering", "type": "DRAW_CARD", "target": "SELF", "params": {"amount": 1}}]}', true),
('card_draw_spell', '占卜术', '{"id": "card_draw_spell", "name": "占卜术", "cardType": "SPELL", "cost": 1, "rarity": "BRONZE", "race": [], "job": "中立", "keywords": [], "description": "抽2张牌", "effects": [{"timing": "Entering", "type": "DRAW_CARD", "target": "SELF", "params": {"amount": 2}}]}', true),
('basic_soldier', '士兵', '{"id": "basic_soldier", "name": "士兵", "cardType": "FOLLOW", "cost": 1, "rarity": "BRONZE", "race": ["人类", "士兵"], "job": "中立", "keywords": [], "description": "基础随从单位", "atk": 1, "hp": 2, "effects": []}', true),
('dragon_knight', '龙骑士', '{"id": "dragon_knight", "name": "龙骑士", "cardType": "FOLLOW", "cost": 3, "rarity": "SILVER", "race": ["人类", "龙"], "job": "中立", "keywords": ["突进"], "description": "战吼：如果我方场上有龙族随从，获得+2/+2", "atk": 2, "hp": 3, "effects": [{"timing": "Entering", "type": "SCRIPT", "script": "buff_if_dragon", "params": {"buffAtk": 2, "buffHp": 2}}]}', true),
('iron_sword', '铁剑', '{"id": "iron_sword", "name": "铁剑", "cardType": "EQUIP", "cost": 2, "rarity": "BRONZE", "race": ["武器"], "job": "战士", "keywords": [], "description": "装备后获得+2攻击力", "addAtk": 2, "durability": 3, "effects": []}', true),
('battle_standard', '战旗', '{"id": "battle_standard", "name": "战旗", "cardType": "AMULET", "cost": 3, "rarity": "SILVER", "race": [], "job": "战士", "keywords": [], "description": "倒数2。回合结束时，使所有我方随从获得+1/+0", "countdown": 2, "effects": [{"timing": "EndTurn", "type": "BUFF", "script": "buff_all_allies", "params": {"buffAtk": 1, "buffHp": 0}}]}', true),
('flame_mage', '火焰法师', '{"id": "flame_mage", "name": "火焰法师", "cardType": "FOLLOW", "cost": 3, "rarity": "SILVER", "race": ["人类", "法师"], "job": "法师", "keywords": [], "description": "战吼：对敌方主战者造成2点伤害", "atk": 2, "hp": 3, "effects": [{"timing": "Entering", "type": "DEAL_DAMAGE", "target": "ENEMY_LEADER", "params": {"amount": 2}}]}', true);
