-- Spring Session JDBC 表结构 (PostgreSQL)
-- 用于存储HTTP Session到数据库

-- 1. Session主表
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

-- Session ID索引，用于快速查找
CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);

-- 过期时间索引，用于清理过期Session
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);

-- 用户名索引，用于查找特定用户的Session
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);


-- 2. Session属性表
CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) 
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

-- 说明：
-- SPRING_SESSION: 存储Session元数据（ID、创建时间、最后访问时间、过期时间等）
-- SPRING_SESSION_ATTRIBUTES: 存储Session中的属性（如用户ID、用户名等）
-- 
-- Session会自动过期清理，Spring Session会定期删除EXPIRY_TIME小于当前时间的记录
-- 
-- 使用方法：
-- 1. 在Supabase SQL编辑器中执行以上SQL
-- 2. 重启应用，Spring Session会自动使用数据库存储Session
-- 3. Session数据会在SPRING_SESSION_ATTRIBUTES表中以二进制形式存储
